version: "3"
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      APP_NAME: corrida
      ELASTICSEARCH_HOST: "elasticsearch"
      ELASTICSEARCH_PORT: 9200
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - .:/home/app/node_docker
      - /home/app/node_docker/node_modules
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: elastic
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
